### ISSUE TITLE
Drawable.draw(canvas) not working lollipop and pre-lollipop

### ISSUE THREAD

**Issue by saveendhiman** [dbof10/FBReaction#3]
hi, i'm not getting why its not working lollipop and pre-lollipop. If you have any idea please suggest.

imageBound.set((int)x,(int) y, (int)x + size, (int)y + size);
imageDrawable.setBounds(imageBound);
imageDrawable.draw(canvas);

**Comment by dbof10** [comment]
Could you provide more information? Your environment, step to reproduce?

**Comment by saveendhiman** [comment]
Thanks for reply, 

I have tried to customized few things like remove json files and use drawable png images or svg images. I  need to use it in list view. Here is my code.  https://github.com/saveendhiman/FacebookReaction/blob/master/app/src/main/java/com/facebookreactions/reaction/Emotion.java

It worked well in android M, N and O(Preview) but not working in lollipop and pre-lollipop. 
I have one more problem it not adjust according to size of different os version. 
If you time please run my code and see what am i missing. 

Thanks alot for reply. :)

**Comment by saveendhiman** [comment]
Hey,  got the issue. 

I have added it as a popup window then it not worked with lollipop and below lolliopop But if i used reaction view add as a root view then it worked.

Confusing why it is not working with popup window.
