### ISSUE TITLE
Reactions are not well showing

### ISSUE THREAD

**Issue by mahermeg17** [dbof10/FBReaction#5]
Hi,
I make some changes to show reactions for each item in a recyclerview. can see changes here : 
https://github.com/mahermeg17/FBReaction/commit/10183f0177749b4c37aec9c98d35c624d5d609a6

But reactions are not well shown. Any help please?
![device-2017-12-26-145453](https://user-images.githubusercontent.com/4602688/34358158-707aeea0-ea4d-11e7-917a-4a408e027a30.png)

**Comment by dbof10** [comment]
`root_frame` is clipped `llFeedInfo`. Use `itemView` instead would work

**Comment by RiteshAdulkar** [comment]
Hey @mahermeg17, i tried in your way to show a reaction on each item in a recycler view, but somehow it doesn't work `root_frame` or either `itemVIew`. @dbof10 Can you please tell me, how would i do that. It should show above the **like** frame.

**Comment by dbof10** [comment]
Can you provide more information?

**Comment by RiteshAdulkar** [comment]
I understood how it needs to be displayed inside a particular view to show a reaction. Just want to know, remove the reaction view in the same way you add. 
Here is the code of onLikeClick

`if (isVisible) {
            isVisible = false;
           rootFrame.removeView(rvl);
        } else {
            isVisible = true;
            rvl.bringToFront();
            rootFrame.addView(rvl);
        }`

but calling removeView, nothing is happening. It shows as it is.
