### ISSUE TITLE
Change the emotion medium size

### ISSUE THREAD

**Issue by sopharasum** [dbof10/FBReaction#8]
Whenever I am trying to increase the emotion medium size and after we hover move horizon space between emotion is large.
For example I have change the Emotion.MEDIUM_SIZE = 45

**Comment by dbof10** [comment]
I think you need to tweek other number


  ```
static final int SMALL_SIZE = DisplayUtil.dpToPx(24);
  static final int MEDIUM_SIZE = DisplayUtil.dpToPx(32);
  static final int LARGE_SIZE = DisplayUtil.dpToPx(72);

  private static final int SPACING_TO_LABEL = DisplayUtil.dpToPx(16);
  private static final int MAX_WIDTH_TITLE = DisplayUtil.dpToPx(56);
```

Those numbers I found work best for me. if you want to change Medium size you need to change other values as well

**Comment by sopharasum** [comment]
> I think you need to tweek other number
> 
> ```
> static final int SMALL_SIZE = DisplayUtil.dpToPx(24);
> static final int MEDIUM_SIZE = DisplayUtil.dpToPx(32);
> static final int LARGE_SIZE = DisplayUtil.dpToPx(72);
> 
> private static final int SPACING_TO_LABEL = DisplayUtil.dpToPx(16);
> private static final int MAX_WIDTH_TITLE = DisplayUtil.dpToPx(56);
> ```
> 
> Those numbers I found work best for me. if you want to change Medium size you need to change other values as well

Thank you for your response. I have play around for increase emotion size. However, I can't increase the emotion label size as well. Please help on this. Thank you.

**Comment by dbof10** [comment]
can you tell me more what is label size? do you have a screenshot?

**Comment by sopharasum** [comment]
> can you tell me more what is label size? do you have a screenshot?

Please refer to my screenshot which show like label on like emoji.
![Screenshot from 2020-12-03 15-36-36](https://user-images.githubusercontent.com/31350036/100985115-29e5a780-357e-11eb-8348-c9209590b947.png)

**Comment by dbof10** [comment]
go to `view_label.xml` and change

**Comment by sopharasum** [comment]
> go to `view_label.xml` and change

I have tried to increase `textSize` and `layout_width` with `layout_height` wrap content in `view_label.xml`, but the label size is not changed. Also I have changed the `label_width` and `label_height` in `dimens.xml` as well. Still nothing changed.

Please refer to my changed below:
**`view_label`**
`<?xml version="1.0" encoding="utf-8"?>`
`<TextView xmlns:android="http://schemas.android.com/apk/res/android"`
   ` xmlns:tools="http://schemas.android.com/tools"`
    `android:layout_width="wrap_content"`
    `android:layout_height="wrap_content"`
    `android:background="@drawable/label_background"`
    `android:gravity="center"`
   ` android:textSize="18sp"`
    `android:textColor="@android:color/white"`
   ` tools:text="Angry" />`

and **`dimens.xml`**
`<dimen name="label_width">65dp</dimen>`
`<dimen name="label_height">32dp</dimen>`
